### ISSUE TITLE
nullpointer exception

### ISSUE THREAD

**Issue by sakulstra** [akexorcist/Android-BluetoothSPPLibrary#18]
Hello,
Is there a working example anywhere except for the few lines in the readme file?
Where does this line come from? 
```setup(); ```
when following the github instructions i get a nullpointer exception when trying to connect to a device. I would appreciate any help :)
Regards,
Lukas
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=384, result=-1, data=Intent { (has extras) }} to activity {com.example.lukas.bluetoothgraph/com.example.lukas.bluetoothgraph.MainInterface}: java.lang.NullPointerException
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3592)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3635)
            at android.app.ActivityThread.access$1300(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5407)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:855)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at app.akexorcist.bluetotohspp.library.BluetoothSPP.connect(BluetoothSPP.java:230)
            at com.example.lukas.bluetoothgraph.MainInterface.onActivityResult(MainInterface.java:38)
            at android.app.Activity.dispatchActivityResult(Activity.java:5469)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3588)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3635)
            at android.app.ActivityThread.access$1300(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5407)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:855)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
            at dalvik.system.NativeStart.main(Native Method)

```

**Comment by PondThaitay** [comment]
Hi sakulstra method setup(); is test send Text.
public void setup() {
		Button btnSend = (Button)findViewById(R.id.btnSend);
		btnSend.setOnClickListener(new OnClickListener(){
        	public void onClick(View v){
        		bt.send("Text", true);
        	}
        });
	}

**Comment by ryazmin** [comment]
You got null pointer exception because you not setup and started bluetooth service.

mBluetoothSPP = new BluetoothSPP(getContext());
if (!mBluetoothSPP.isBluetoothAvailable()) {
    //oops, don't have bluetooth
    return;
}
if (!mBluetoothSPP.isBluetoothEnabled()) {
    //bluetooth is turned off, let's try to turn it on
    mBluetoothSPP.enable();
}
mBluetoothSPP.setupService(); // setup bluetooth service
mBluetoothSPP.startService(true); // start bluetooth service

**Comment by sakulstra** [comment]
thx :)

**Comment by vidyajejurkar** [comment]
@ryazmin 
I am using below code but I didn't understand purpose of send button and I am getting error nullpointerexception

package in.harman.android_barcode_scanner;

import android.os.Bundle;
import android.app.Activity;
import android.content.Intent;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.Toast;
import app.akexorcist.bluetotohspp.library.BluetoothSPP;
import app.akexorcist.bluetotohspp.library.BluetoothSPP.OnDataReceivedListener;
import app.akexorcist.bluetotohspp.library.BluetoothState;
import app.akexorcist.bluetotohspp.library.DeviceList;

public class BluetoothConnectionActivity extends Activity {
    BluetoothSPP bt;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_devicelist);

        bt = new BluetoothSPP(getApplicationContext());

        if(!bt.isBluetoothAvailable()) {
            Toast.makeText(getApplicationContext()
                    , "Bluetooth is not available"
                    , Toast.LENGTH_SHORT).show();
            finish();
        }

        bt.setOnDataReceivedListener(new OnDataReceivedListener() {
            public void onDataReceived(byte[] data, String message) {
                Log.i("Check", "Length : " + data.length);
                Log.i("Check", "Message : " + message);
            }
        });

        Button btnConnect = (Button)findViewById(R.id.btnConnect);
        btnConnect.setOnClickListener(new OnClickListener(){
            public void onClick(View v){
                if(bt.getServiceState() == BluetoothState.STATE_CONNECTED) {
                    bt.disconnect();
                } else {
                    Intent intent = new Intent(BluetoothConnectionActivity.this, DeviceList.class);
                    intent.putExtra("bluetooth_devices", "Bluetooth devices");
                    intent.putExtra("no_devices_found", "No device");
                    intent.putExtra("scanning", "Scanning");
                    intent.putExtra("scan_for_devices", "Search");
                    intent.putExtra("select_device", "Select");
                    intent.putExtra("layout_list", R.layout.device_layout_list);
                    intent.putExtra("layout_text", R.layout.device_layout_text);
                    startActivityForResult(intent, BluetoothState.REQUEST_CONNECT_DEVICE);
                }
            }
        });
    }

    public void onDestroy() {
        super.onDestroy();
        bt.stopService();
    }

    public void onStart() {
        super.onStart();
        if(!bt.isBluetoothEnabled()) {
            bt.enable();
        } else {
            if(!bt.isServiceAvailable()) {
                bt.setupService();
                bt.startService(BluetoothState.DEVICE_ANDROID);
                //setup();
            }
        }
    }

    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if(requestCode == BluetoothState.REQUEST_CONNECT_DEVICE) {
            if(resultCode == Activity.RESULT_OK)
                Toast.makeText(getApplicationContext(),"Connected",Toast.LENGTH_LONG).show();
                bt.connect(data);
        } else if(requestCode == BluetoothState.REQUEST_ENABLE_BT) {
            if(resultCode == Activity.RESULT_OK) {
                bt.setupService();
                Toast.makeText(getApplicationContext(),"Enable_BT",Toast.LENGTH_LONG).show();

            } else {
                Toast.makeText(getApplicationContext()
                        , "Bluetooth was not enabled."
                        , Toast.LENGTH_SHORT).show();
                finish();
            }
        }
    }

    public void setup() {
        Button btnSend = (Button)findViewById(R.id.btnSend);
        btnSend.setOnClickListener(new OnClickListener(){
            public void onClick(View v){
                bt.send("Text", true);
            }
        });
    }
}

**Comment by ryazmin** [comment]
@vidyajejurkar send button will send "Text" to connected device over bluetooth. If you getting NPE then something wrong, stack trace will be helpful.

**Comment by vidyajejurkar** [comment]
@ryazmin  Thanks for Reply :-)
I have one Question. I am using this library for Connection but I think they used BluetoothChat as it is which I don't want to do. instead of Chatting I want to send my app data like table to device which is supporting BluetoothSpp.
So how to modified it?
Need help.

**Comment by ryazmin** [comment]
@vidyajejurkar I guess it's a question about how you representing your data on one end and how you interpreted it on another end.
Can you represent your data as json, for example? If so, just put your data to json, then take a string representation of json and send this string over bluetooth. On another end you will get this string, take it and construct the json from it. Now you can extract your data from json.

**Comment by vidyajejurkar** [comment]
Ok @ryazmin  N I am facing one problem. sometime device gets connected sometime don't.

D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
I/Timeline: Timeline: Activity_launch_request id:in.harman.android_barcode_scanner time:106607876
D/DisplayManager: DisplayManager()
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b37ae56 time:106608009
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/BluetoothSPP: doDiscovery()
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/BluetoothSPP: doDiscovery()
D/BluetoothSocket: close() in, this: android.bluetooth.BluetoothSocket@314f881e, channel: -1, state: CLOSED
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/Bluetooth Service: setState() 1 -> 2
D/BluetoothUtils: isSocketAllowedBySecurityPolicy start : device null
D/BluetoothSocket: connect(): myUserId = 0
W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothSocket: connect(), SocketState: INIT, mPfd: {ParcelFileDescriptor: FileDescriptor[44]}
D/OpenGLRenderer: endAllStagingAnimators on 0xb8001148 (ListView) with handle 0xb7fcabc8
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2db363c8 time:106618111
D/BluetoothSocket: close() in, this: android.bluetooth.BluetoothSocket@2f12575c, channel: -1, state: INIT
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@2f12575c, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@e956a65, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@2b27433amSocket: android.net.LocalSocket@f0f7beb impl:android.net.LocalSocketImpl@241b8d48 fd:FileDescriptor[44]
D/BluetoothSocket: Closing mSocket: android.net.LocalSocket@f0f7beb impl:android.net.LocalSocketImpl@241b8d48 fd:FileDescriptor[44]
D/BluetoothSocket: close() in, this: android.bluetooth.BluetoothSocket@2f12575c, channel: -1, state: CLOSED
D/Bluetooth Service: setState() 2 -> 1

**Comment by ciestowp** [comment]
> You got null pointer exception because you not setup and started bluetooth service.
> 
> mBluetoothSPP = new BluetoothSPP(getContext());
> if (!mBluetoothSPP.isBluetoothAvailable()) {
> //oops, don't have bluetooth
> return;
> }
> if (!mBluetoothSPP.isBluetoothEnabled()) {
> //bluetooth is turned off, let's try to turn it on
> mBluetoothSPP.enable();
> }
> mBluetoothSPP.setupService(); // setup bluetooth service
> mBluetoothSPP.startService(true); // start bluetooth service

Please include mBluetoothSPP.setupService(); in readme section also

**Comment by goherhussain** [comment]
I am sending data from arduino but I didnt get any data

bt.setOnDataReceivedListener(new BluetoothSPP.OnDataReceivedListener() {
            @Override
            public void onDataReceived(byte[] data, String message) {
                mTextView.setText(message);
                Toast.makeText(getApplicationContext(), "Message is :"+message, Toast.LENGTH_SHORT).show();
            }
        });
ITS NOT WORKING

**Comment by hetthummar** [comment]
Thanks ,it works .
