### ISSUE TITLE
Device List Activity

### ISSUE THREAD

**Issue by anuchin** [akexorcist/Android-BluetoothSPPLibrary#23]
Hey, i am new to Android Programming.
I am encountering a problem. After I use the Intent to choose device activity and when I check result data on onActivityResult, i get an error  at bt.connect(data), can you pls explain what does bt.connect does? Is it used to to connect to the device? Does the variable ' data' contain the Mac address?
I've declared the library and activity and every other feature works fine. Can u help me?
A Sample program using the commands will help me immensely, if u have it.
Thanks for this Library.

**Comment by ryazmin** [comment]
What error do you get?
I guess you not started service with:
bt.setupService();
bt.startService(BluetoothState.DEVICE_ANDROID);

Yes, intent 'data' contains mac address of bluetooth device.
The library will extract it and use for connection.

**Comment by anuchin** [comment]
Thank you, for your reply, So i have to use 
bt.setupService();
bt.startService(BluetoothState.DEVICE_ANDROID);
before using bt.connect(data);?
then bt.send()?

here is my program, This is to onnect to the device

public void Connect(View view){
        if(!bt.isBluetoothEnabled()) {
            Toast.makeText(getApplicationContext(),"Please Switch On Bluetooth",Toast.LENGTH_LONG).show();
        } else {
            Intent intent = new Intent(getApplicationContext(), DeviceList.class);
            startActivityForResult(intent, BluetoothState.REQUEST_CONNECT_DEVICE);
        }
    }

then 
public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if(requestCode == BluetoothState.REQUEST_CONNECT_DEVICE) {
            if(resultCode == Activity.RESULT_OK)
                bt.setupService();
                bt.startService(BluetoothState.DEVICE_OTHER);
                bt.connect(data);
        } else if(requestCode == BluetoothState.REQUEST_ENABLE_BT) {
            if(resultCode == Activity.RESULT_OK) {
                bt.setupService();
                bt.startService(BluetoothState.DEVICE_OTHER);
                setup();
            } else {
                // Do something if user doesn't choose any device (Pressed back)
            }
        }
    }

after that i use
public void Send(View view){
        bt.send("a",true);
}

but i don't receive any data, what do you think is the problem?

**Comment by lucagessi** [comment]
Hi! I have a problem sending data to device!! 
It seems to always need functions setupService and startService to be called before every send(...) call.
Then what's the setup() function? 
Thanks

**Comment by anuchin** [comment]
i just removed it and then it worked fine :)
