### ISSUE TITLE
notifying sending task is finished

### ISSUE THREAD

**Issue by membrown** [akexorcist/Android-BluetoothSPPLibrary#43]
How can i notify when bt.send() task is finished ?
thanks.

**Comment by alireza59** [comment]
Hi membrown, Did you find anything for this issue?

**Comment by SeynalKim** [comment]
@membrown hello!, did you solve this problem?

**Comment by membrown** [comment]
hello, i switched to android standard API library (developer.android.com) and my problem solved.
