### ISSUE TITLE
How can I import and use this project in eclipse?

### ISSUE THREAD

**Issue by FantaZy** [akexorcist/Android-BluetoothSPPLibrary#5]
Can someone explain that?

**Comment by akexorcist** [comment]
You can import directly to eclipse by choose Android > Import from existing project

**Comment by bernabap** [comment]
When I import to eclipse it creates 2 projects "DeviceList" and "Main", non of them is marked as library and their "src" folder are empty. Are you using Eclipse to develop this library?

**Comment by akexorcist** [comment]
I make an article about this question. but it's thai language.
Instead, look at the picture in an article
http://www.akexorcist.com/2015/02/move-android-studio-project-to-eclipse-adt.html
